In [13]:
print("eelo")

eelo

In [14]:
import pandas as pd
df=pd.read_csv("data.csv")
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [15]:
df.sort_values('Year',ascending=False)

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [16]:
df2=df.sort_values(["Year","IMDb"],ascending=[False,False]).copy()
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,Hrithik Roshan,War,2019,Action,475,6.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [17]:
df2.reset_index(drop=True,inplace=True)

In [18]:
df2["Rank"]=df["IMDb"].rank(method="dense")

In [19]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,7.0
1,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,3.0
2,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
3,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,1.0
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
5,Hrithik Roshan,War,2019,Action,475,6.5,10.0
6,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,8.0
7,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,5.0
8,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
9,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,2.0
10,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,4.0
11,Aamir Khan,Dangal,2016,Biography,2024,8.4,9.0

melt

In [20]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [90, 82, 89],
    'English': [88, 85, 94]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       85
2  Charlie    92       89       94

mergee

In [21]:
import pandas as pd


employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [22]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [23]:
pd.merge(employees, departments, on="DeptID", how="inner")

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [24]:
pd.merge(employees, departments, on="DeptID", how="outer")

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [26]:
df2.to_csv("dataupadted.csv")